# Site settings
title: "The Dark Sunshine"
email: contact@priyesh.dev
description: "My Poetry Blog."
baseurl: "https://codejockey02.github.io/myhobbyblog/"
url: "https://codejockey02.github.io/myhobbyblog/"
title_description: "Welcome to my Blog. Here I post some poetry/writeups on some little things in life that we tend to ignore."
title_image: "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTxEOVTcvf8wEI1bGPVZrCVADRvWGpFsVzrowss8S1SuQl_xJjK"
disqus_account: cartenoire
post_limit: 5

# Social usernames/URLs
twitter_username: __priyesh
instagram_username: the.dark.sunshine

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> using Jekyll."
footer_right: "&lt;/&gt; on <a href=\"https://github.com/codejockey02/myhobbyblog\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
