# Site settings
title: "The Dark Sunshine"
email: contact@priyesh.dev
description: "My Poetry Blog."
baseurl: "https://poetry.priyesh.dev"
url: "https://poetry.priyesh.dev"
title_description: "Finding my way to escape this labyrinth."
author_description: "(A Poetry Blog by Priyesh Saraswat.)"
title_image: "https://document-export.canva.com/DADyId3sDBs/57/thumbnail/0001-6232456043.png"
disqus_account: cartenoire
post_limit: 5

# Social usernames/URLs
twitter_username: __priyesh
instagram_username: the.dark.sunshine

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> using Jekyll."
footer_right: "&lt;/&gt; on <a href=\"https://github.com/codejockey02/myhobbyblog\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
