# Site settings
title: "The Dark Sunshine"
email: contact@priyesh.dev
description: "My Poetry Blog."
baseurl: "https://codejockey02.github.io/myhobbyblog/"
url: "https://codejockey02.github.io/myhobbyblog/"
title_description: "Finding my way to escape this labyrinth."
title_image: "https://instagram.fbom3-1.fna.fbcdn.net/v/t51.2885-19/s150x150/82941592_213919546313564_4561668049068883968_n.jpg?_nc_ht=instagram.fbom3-1.fna.fbcdn.net&_nc_ohc=tCLjeA9ox_EAX9ESowX&oh=dac8fbfcc71f43722cd59222dd7d01de&oe=5EC18F88"
disqus_account: cartenoire
post_limit: 5

# Social usernames/URLs
twitter_username: __priyesh
instagram_username: the.dark.sunshine

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> using Jekyll."
footer_right: "&lt;/&gt; on <a href=\"https://github.com/codejockey02/myhobbyblog\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
